force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <description>Relates to a Customer record in Stripe</description>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Stripe Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Customer ID</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Stripe Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Checkout_URL__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Url__c</fullName>
    <label>Checkout Url</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of subscriptions for purchase.</description>
    <inlineHelpText>Number of subscriptions for purchase. Defaults to 1</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Checkout__c</fullName>
    <label>Stripe Checkout Session Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Checkout Created</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Outbound Integration/CreateStripeCheckoutSessionQueuable.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Queueable class to perform asynchronous processing of Stripe Checkout Session creation
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-14
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-05 v1.0.0 Initial creation
 * -----------------------------------------------------------------------------
 */
public with sharing class CreateStripeCheckoutSessionQueuable implements Queueable, Database.AllowsCallouts {
  // Add any parameters you need to pass to the queueable
  private Id stripeSubscriptionId;

  public CreateStripeCheckoutSessionQueuable(Id stripeSubscriptionId) {
    this.stripeSubscriptionId = stripeSubscriptionid;
  }

  public void execute(QueueableContext context) {
    Stripe_Subscription__c subscription = [
      SELECT
        Id,
        Stripe_Customer__c,
        Stripe_Customer__r.Stripe_Customer_ID__c,
        Currency__c,
        Quantity__c,
        Price_ID__c
      FROM Stripe_Subscription__c
      WHERE Id = :stripeSubscriptionId
      LIMIT 1
    ];

    //Prepare the request for Stripe Checkout Session
    CheckoutSessionWrapper sessionRequest = new CheckoutSessionWrapper();
    sessionRequest.customer = subscription.Stripe_Customer__r.Stripe_Customer_ID__c;
    sessionRequest.mode = 'subscription';
    sessionRequest.success_url = Redirect_URL__mdt.getInstance(
        'Payment_Successful'
      )
      .Redirect_URL__c;
    sessionRequest.cancel_url = Redirect_URL__mdt.getInstance(
        'Payment_Cancelled'
      )
      .Redirect_URL__c;

    sessionRequest.line_items = new List<CheckoutSessionWrapper.LineItem>();
    sessionRequest.currency_code = subscription.Currency__c;

    CheckoutSessionWrapper.LineItem lineItem = new CheckoutSessionWrapper.LineItem();
    lineItem.price = subscription.Price_ID__c; // Assuming this is the price ID

    if (subscription.Quantity__c == null) {
      lineItem.quantity = 1; // Default to 1 if quantity is not set
    } else {
      lineItem.quantity = (Integer) subscription.Quantity__c;
    }
    sessionRequest.line_items.add(lineItem);

    System.debug(
      'Creating Checkout Session for Subscription: ' + subscription.Id
    );
    System.debug('Session Request: ' + sessionRequest);

    //Call the Stripe API to create a checkout session
    CheckoutSessionWrapper checkoutSession = StripeAPIClient.createCheckoutSession(
      sessionRequest
    );

    Logger.debug('Checkout Session Response: ' + checkoutSession);
    Logger.saveLog();

    // Handle the response from Stripe
    if (checkoutSession != null && checkoutSession.id != null) {
      // Update the Stripe_Subscription__c record with the session ID
      subscription.Stripe_Checkout__c = checkoutSession.id;
      subscription.Sync_Status__c = 'Checkout Created';
      subscription.Checkout_URL__c = checkoutSession.url;

      try {
        update subscription;
      } catch (DMLException e) {
        Logger.error('Error updating subscription: ' + e.getMessage());
        Logger.saveLog();
      }
    }
  }
}