force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <description>Relates to a Customer record in Stripe</description>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Stripe Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Customer ID</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Stripe Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_End__c</fullName>
    <label>Current Period End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_Start__c</fullName>
    <label>Current Period Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>day</fullName>
            </value>
            <value>
                <fullName>week</fullName>
            </value>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Incomplete Expired</fullName>
            </value>
            <value>
                <fullName>Trialing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Checkout Session Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Id__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateStripeSubscriptionQueuable.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Queueable class to perform asynchronous processing of Subscriptions
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-05
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-05 v1.0.0 Initial creation
 *  - 2025-06-12 v1.0.1 Added logic to prevent recursion by bypassing triggers
 * -----------------------------------------------------------------------------
 */
public with sharing class CreateStripeSubscriptionQueuable implements Queueable, Database.AllowsCallouts {
  private Id stripeSubscriptionId;

  public CreateStripeSubscriptionQueuable(Id stripeSubscriptionId) {
    this.stripeSubscriptionId = stripeSubscriptionId;
  }

  public void execute(QueueableContext context) {
    // Retrieve the Stripe_Subscription__c record
    Stripe_Subscription__c subscription = [
      SELECT
        Id,
        Status__c,
        Stripe_Customer__c,
        Stripe_Customer__r.Stripe_Customer_ID__c,
        Amount__c,
        Currency__c,
        Interval__c,
        Product_Name__c,
        Subscription_Id__c,
        Current_Period_Start__c,
        Current_Period_End__c
      FROM Stripe_Subscription__c
      WHERE Id = :stripeSubscriptionId
      LIMIT 1
    ];

    String stripeCustomerId = subscription.Stripe_Customer__r.Stripe_Customer_ID__c;
    //Stripe API requires sending amount in cents and as an Integer, so we muliply by 100 and convert to Integer
    Decimal amountDecimal = subscription.Amount__c * 100;
    Integer amount = (Integer) amountDecimal;
    String currencyCode = subscription.Currency__c;
    String interval = subscription.Interval__c;
    String productName = subscription.Product_Name__c;

    //Create Product in Stripe
    String productId = StripeAPIClient.createProduct(productName);

    //Create Price Object in Stripe
    String priceId = StripeAPIClient.createPrice(
      productId,
      amount,
      currencyCode,
      interval
    );

    // Prepare Subscription Request
    SubscriptionsWrapper sw = new SubscriptionsWrapper();
    sw.customer = stripeCustomerId;

    SubscriptionsWrapper.ItemWrapper iw = new SubscriptionsWrapper.ItemWrapper();
    iw.data = new List<SubscriptionsWrapper.Item>();

    SubscriptionsWrapper.Item item = new SubscriptionsWrapper.Item();
    item.price = new SubscriptionsWrapper.Price();
    item.price.id = priceId; // Set the price ID created above

    iw.data.add(item);
    sw.items = iw;

    //Call Stripe to Create Subscription
    try {
      SubscriptionsWrapper stripeSubscription = StripeAPIClient.createSubscription(
        sw
      );
      Logger.debug('Stripe Subscription created: ' + stripeSubscription);
      Logger.saveLog();
      if (stripeSubscription != null) {
        subscription.Subscription_Id__c = stripeSubscription.id;
        subscription.Current_Period_Start__c = SubscriptionsWrapper.convertUnixToDatetime(
          stripeSubscription.items.data[0].current_period_start
        );
        subscription.Current_Period_End__c = SubscriptionsWrapper.convertUnixToDatetime(
          stripeSubscription.items.data[0].current_period_end
        );
        subscription.Status__c = stripeSubscription.status;
        subscription.Price_ID__c = stripeSubscription.items.data[0].price.id;

        TriggerBypass.bypassStripeSubscription = true; // Bypass trigger to avoid recursion
        update subscription;
        TriggerBypass.bypassStripeSubscription = false; // Reset bypass after update
      }
    } catch (Exception e) {
      Logger.error('Error creating Stripe Subscription: ' + e.getMessage());
      Logger.saveLog();
      throw new CalloutException(
        'Error creating Stripe Subscription: ' + e.getMessage()
      );
    }
  }
}