force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <description>Relates to a Customer record in Stripe</description>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Stripe Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Outbound Integration/StripeCustomerTriggerHandler.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Queueable class to perform asynchronous processing of Stripe Checkout Session creation
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-05
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-05 v1.0.0 Initial creation
 *  - 2025-06-14 v1.0.1 Added logic to prevent recursion by bypassing triggers
 * -----------------------------------------------------------------------------
 */
public with sharing class StripeCustomerTriggerHandler {
  /*
  description: afterInsert method to handle the creation of Stripe customers by calling the Stripe API via a Queueable class.
  @param newList: List<Stripe_Customer__c> - The list of newly inserted Stripe_Customer__c records.
  */
  public static void afterInsert(List<Stripe_Customer__c> newList) {
    List<Stripe_Customer__c> customersToUpdate = new List<Stripe_Customer__c>();

    for (Stripe_Customer__c customer : newList) {
      if (TriggerBypass.bypassStripeCustomer == false) {
        try {
          // Create a Stripe customer using the Stripe API client
          StripeCustomerWrapper.CustomerRequest customerRequest = new StripeCustomerWrapper.CustomerRequest();
          customerRequest.name = customer.Name;
          customerRequest.email = customer.Email__c;
          customerRequest.phone = customer.Phone__c;

          // Call the Stripe API to create the customer
          System.enqueueJob(new CreateStripeCustomerQueuable(customer.Id));
        } catch (Exception e) {
          Logger.error('Error creating Stripe customer: ' + e.getMessage());
          Logger.saveLog();
        }
      }
    }
    update customersToUpdate;
  }
}