force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <description>Relates to a Customer record in Stripe</description>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Stripe Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Stripe Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Incomplete Expired</fullName>
            </value>
            <value>
                <fullName>Trialing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Checkout Session Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Outbound Integration/StripeSubscriptionTriggerHandler.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Trigger Handler for Stripe Subscription operations
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-12
 * LAST EDITED :
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-07 v1.0.0 Initial creation
 *  - 2025-06-12 v1.0.1 Added support for creating checkout sessions
 * -----------------------------------------------------------------------------
 */
public with sharing class StripeSubscriptionTriggerHandler {
  public static void afterInsert(List<Stripe_Subscription__c> newList) {
    List<Stripe_Subscription__c> subscriptionsToUpdate = new List<Stripe_Subscription__c>();

    for (Stripe_Subscription__c subscription : newList) {
      if (TriggerBypass.bypassStripeSubscription == false) {
        try {
          // Call the Stripe API to create the customer
          System.enqueueJob(
            new CreateStripeSubscriptionQueuable(subscription.Id)
          );
        } catch (Exception e) {
          Logger.Error(
            'Error creating Stripe subscription for ' + subscription.Id,
            e
          );
          Logger.saveLog();
        }
      }
    }
    update subscriptionsToUpdate;
  }

  /*
  description: afterUpdate method to handle updates to Stripe customers.
  @param newList: List<Stripe_Customer__c> - The list of updated Stripe_Customer__c records.
  @param oldMap: Map<Id, Stripe_Customer__c> - The map of old Stripe_Customer__c records before the update.
  */
  public static void afterUpdate(
    List<Stripe_Subscription__c> newList,
    Map<Id, Stripe_Subscription__c> oldMap
  ) {
    for (Stripe_Subscription__c subscription : newList) {
      Stripe_Subscription__c oldSubscription = oldMap.get(subscription.Id);

      //Handle Price Change
      if (
        oldSubscription != null &&
        oldSubscription.Price_ID__c == subscription.Price_ID__c &&
        oldSubscription.Amount__c != subscription.Amount__c
      ) {
        try {
          System.enqueueJob(
            new UpdateStripeSubscriptionQueuable(subscription.Id, 'update')
          );
        } catch (Exception e) {
          Logger.error(
            'Error updating Stripe subscription for ' + subscription.Id,
            e
          );
          Logger.saveLog();
        }

        //Handle Subscription Cancellation
        if (
          oldSubscription != null &&
          oldSubscription.Status__c != subscription.Status__c &&
          subscription.Status__c == 'canceled'
        ) {
          try {
            System.enqueueJob(
              new UpdateStripeSubscriptionQueuable(subscription.Id, 'cancel')
            );
          } catch (Exception e) {
            Logger.error(
              'Error canceling Stripe subscription for ' + subscription.Id,
              e
            );
            Logger.saveLog();
          }
        }

        //Handle Subscription Price Update for First Time
        if (
          oldSubscription.Price_ID__c == null &&
          oldSubscription.Price_ID__c != subscription.Price_ID__c &&
          subscription.Status__c == 'Incomplete'
        ) {
          try {
            System.enqueueJob(
              new CreateStripeCheckoutSessionQueuable(subscription.Id)
            );
          } catch (Exception e) {
            Logger.error(
              'Error updating Stripe subscription for ' + subscription.Id,
              e
            );
            Logger.saveLog();
          }
        }
      }
    }
  }
}