force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Stripe Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_End__c</fullName>
    <label>Current Period End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_Start__c</fullName>
    <label>Current Period Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>day</fullName>
            </value>
            <value>
                <fullName>week</fullName>
            </value>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of subscriptions for purchase.</description>
    <inlineHelpText>Number of subscriptions for purchase. Defaults to 1</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Incomplete Expired</fullName>
            </value>
            <value>
                <fullName>Trialing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Checkout Session Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Id__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Outbound Integration/UpdateStripeSubscriptionQueuable.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Queueable class to perform asynchronous processing of Updating Subscriptions
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-05
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-07 v1.0.0 Initial creation
 * -----------------------------------------------------------------------------
 */
public with sharing class UpdateStripeSubscriptionQueuable implements Queueable, Database.AllowsCallouts {
  private Id stripeSubscriptionId;
  private String operationType;

  public UpdateStripeSubscriptionQueuable(
    Id stripeSubscriptionId,
    String operationType
  ) {
    this.stripeSubscriptionId = stripeSubscriptionId;
    this.operationType = operationType;
  }

  public void execute(QueueableContext context) {
    // Retrieve the Stripe_Subscription__c record
    Stripe_Subscription__c subscription = [
      SELECT
        Id,
        Status__c,
        Amount__c,
        Currency__c,
        Quantity__c,
        Price_ID__c,
        Subscription_ID__c,
        Current_Period_Start__c,
        Current_Period_End__c,
        Product_ID__c,
        Interval__c
      FROM Stripe_Subscription__c
      WHERE Id = :stripeSubscriptionId
      LIMIT 1
    ];

    //If Quantity or Price change, create a new Price in Stripe and Generate a new Checkout Session
    if (operationType == 'update') {
      try {
        // Create a new Price in Stripe
        String productId = subscription.Product_ID__c;
        Integer amount = (Integer) (subscription.Amount__c * 100); // Convert to cents
        String currencyCode = subscription.Currency__c;
        String interval = subscription.Interval__c;

        String newPriceId = StripeAPIClient.createPrice(
          productId,
          amount,
          currencyCode,
          interval
        );

        // Update the Price_ID__c field in the subscription record
        subscription.Price_ID__c = newPriceId;
        if (!Test.isRunningTest()) {
          update subscription;
        }
        // Log the successful update
        Logger.debug(
          'Stripe Subscription updated successfully: ' + subscription.Id
        );
        Logger.saveLog();

        // Enqueue a job to create a Stripe Checkout Session
        System.enqueueJob(
          new CreateStripeCheckoutSessionQueuable(subscription.Id)
        );
      } catch (Exception e) {
        Logger.error(
          'Error updating Stripe subscription: ' + e.getMessage(),
          subscription
        );
        Logger.saveLog();
      }
    }
    //Handle Subscription Cancellation
    else if (operationType == 'cancel') {
      try {
        // Call Stripe API to cancel the subscription
        StripeAPIClient.cancelSubscription(subscription.Subscription_ID__c);
        // Update the Stripe_Subscription__c record with the new Status
        subscription.Status__c = 'canceled';
      } catch (Exception e) {
        Logger.error(
          'Error canceling Stripe subscription: ' + e.getMessage(),
          subscription
        );
        Logger.saveLog();
      }
    }
  }
}