force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Stripe Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_End__c</fullName>
    <label>Current Period End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Current_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Current_Period_Start__c</fullName>
    <label>Current Period Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Propration_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Propration_Behavior__c</fullName>
    <description>If you want to charge for an upgrade immediately, pass proration behavior as always invoice to create prorations, automatically invoice the customer for those proration adjustments, and attempt to collect payment. If you pass create prorations, the prorations are created but not automatically invoiced. If you don’t want to prorate, set the proration behavior option to none</description>
    <inlineHelpText>If you want to charge for an upgrade immediately, pass proration behavior as always invoice to create prorations, automatically invoice the customer for those proration adjustments, and attempt to collect payment. If you pass create prorations, the prorations are created but not automatically invoiced. If you don’t want to prorate, set the proration behavior option to none</inlineHelpText>
    <label>Proration Behavior</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>always_invoice</fullName>
            </value>
            <value>
                <fullName>create_prorations</fullName>
            </value>
            <value>
                <fullName>none</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Incomplete Expired</fullName>
            </value>
            <value>
                <fullName>Trialing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Checkout Session Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Id__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateStripeSubscriptionQueuable.cls
/**
 * -----------------------------------------------------------------------------
 * DESCRIPTION : Queueable class to perform asynchronous processing of Updating Customers
 *
 * AUTHOR      : Brian Premo
 * CREATED     : 2025-06-05
 *
 * VERSION     : 1.0.0
 *
 * CHANGE LOG  :
 *  - 2025-06-07 v1.0.0 Initial creation
 * -----------------------------------------------------------------------------
 */
public with sharing class UpdateStripeSubscriptionQueuable implements Queueable, Database.AllowsCallouts {
  private Id stripeSubscriptionId;
  private String operationType;

  public UpdateStripeSubscriptionQueuable(
    Id stripeSubscriptionId,
    String operationType
  ) {
    this.stripeSubscriptionId = stripeSubscriptionId;
    this.operationType = operationType;
  }

  public void execute(QueueableContext context) {
    // Retrieve the Stripe_Subscription__c record
    Stripe_Subscription__c subscription = [
      SELECT
        Id,
        Status__c,
        Amount__c,
        Currency__c,
        Propration_Behavior__c,
        Price_ID__c,
        Subscription_ID__c,
        Current_Period_Start__c,
        Current_Period_End__c
      FROM Stripe_Subscription__c
      WHERE Id = :stripeSubscriptionId
      LIMIT 1
    ];

    //Handle Price ID changes
    if (operationType == 'update') {
      //Prepare Subscription Request
      SubscriptionsWrapper sw = new SubscriptionsWrapper();
      sw.id = subscription.Subscription_ID__c;
      sw.prorationBehavior = subscription.Propration_Behavior__c;

      SubscriptionsWrapper.ItemWrapper iw = new SubscriptionsWrapper.ItemWrapper();
      iw.data = new List<SubscriptionsWrapper.Item>();

      SubscriptionsWrapper.Item item = new SubscriptionsWrapper.Item();
      item.price = new SubscriptionsWrapper.Price();
      item.price.id = subscription.Price_ID__c;

      iw.data.add(item);
      sw.items = iw;

      try {
        SubscriptionsWrapper stripeSubscription = StripeAPIClient.updateSubscription(
          sw
        );
        // Update the Stripe_Subscription__c record with the new Status
        subscription.Status__c = stripeSubscription.status;
      } catch (Exception e) {
        Logger.error(
          'Error updating Stripe subscription: ' + e.getMessage(),
          subscription
        );
        Logger.saveLog();
      }
    }
    //Handle Subscription Cancellation
    else if (operationType == 'cancel') {
      try {
        // Call Stripe API to cancel the subscription
        StripeAPIClient.cancelSubscription(subscription.Subscription_ID__c);
        // Update the Stripe_Subscription__c record with the new Status
        subscription.Status__c = 'canceled';
      } catch (Exception e) {
        Logger.error(
          'Error canceling Stripe subscription: ' + e.getMessage(),
          subscription
        );
        Logger.saveLog();
      }
    }
  }
}